author: "Lionheart Software"
author_url: "https://lionheartsw.com"
github_url: "https://github.com/lionheart/LHSTwitterFollowUtility"
github_file_prefix: "https://github.com/lionheart/LHSTwitterFollowUtility/tree/0.1.0"
xcodebuild_arguments: ["-workspace", "Example/LHSTwitterFollowUtility.xcworkspace", "-scheme", "LHSTwitterFollowUtility"]
readme: "README.md"
copyright: "&copy; 2016-2017 Lionheart Software LLC"
theme: fullwidth
head: "<style type='text/css'>body { font-family: -apple-system !important; }</style>"
use_safe_filenames: true

